### PR TITLE
Null checks on fields

### PR DESCRIPTION
**Pull request by aarahman7**
Whenever we retrieve a value from the json field, we use .toString() which could throw NullPointerException. That field may be allowed to have null but since we have .toString() we would end up with NPE. This PR aims at avoiding such NPE. Its a better alternative to null check.
More info on this approach is [here](https://towardsdev.com/stop-checking-for-nulls-in-java-593a1f1a0c2f)

Note : This PR contains the changes made in #6  too.

### CODE REVIEW

**Comment by shivam1608** [comment]
@aarahmanqa can you resolve the merge conflicts for this pull request after that i'll test the code and merge accordingly.

**Comment by aarahman7** [comment]
@shivam1608 , sorry for delay. I have resolved conflicts. Kindly review it.

**Comment by shivam1608** [comment]
@aarahmanqa  np for delays , currently i don't have my pc with me, i'm using my mobile. i'll soon check the commits when i reach home.

**Comment by aarahman7** [comment]
@shivam1608 , could you please review the PR and get it merged?

**Review by shivam1608 — APPROVED** [review]
Review Completed.
Thanks to @NotTheRambo

**Pull request merged**
